name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies...
      run: yarn install
    - name: Run tests...
      run: yarn test --passWithNoTests
    - name: Create code coverage reports...
      run: yarn test --coverage --watchAll=false --passWithNoTests
    - name: Push code coverage to Codecov...
      run: bash <(curl -s https://codecov.io/bash) -t "$CODECOV_TOKEN"
    - name: Push snapshot to Percy...
      uses: percy/storybook-action@v0.1.2
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
